### PR TITLE
Theory dacathon update: LeadingOnes benchmark added

### PR DESCRIPTION
**Pull request by ndangtt**
Hello,

In this pull request I've updated the Theory benchmark with our latest [LeadingOnes benchmark](https://arxiv.org/abs/2202.03259). The main changes include:

- The benchmark and environment are renamed to TheoryBenchmark and TheoryEnv, and all implementation has been revised with major updates to (hopefully) make the benchmark easier to use for everyone.
- OneLL is now removed from the benchmark, as this is still work-in-progress and under-tested.
- Documentation and examples on how to use the benchmark are available at: https://github.com/automl/DACBench/tree/theory_dacathon/examples/benchmarks/theory

If you have any suggestions on the implementation and the structure, please just let us know!

Thanks,
Nguyen

### CODE REVIEW

**Comment by TheEimer** [comment]
Thanks for the PR, Nguyen, I'll look over it and add comments if any are necessary. I'm excited for the theory benchmarks in general, though, and looking forward to trying them out!

**Comment by TheEimer** [comment]
I added some minor tweaks that came up for me (a minor import issue, the commit hooks) and added ConfigSpace as we're trying to rely more consistently on that instead of the gym API - so nothing important really. everything looks good to me. The examples are running smoothly for me and I only have two points to mention:

- as a comment on the config, it currently says that the two possible problems are "LeadingOne" and "OneMax". I think that's not true for the current version, right? I just wanted to ask before I remove the comment in case OneMax should be included as it doesn't work for me
- did you use the commit hooks that come with the dev installation? Several things came up from flake8 for the two files I modified, so it would be great if you could check both the formatting (with black) and flake's output again.

**Comment by ndangtt** [comment]
Hi @TheEimer, thank you very much for the reviewing and for your kind words on the benchmark! My apologies for missing the flake8 checks. They've been fixed now and I've also removed all OneMax related stuffs from the repo and the comments. 

I just realise that there's still one thing I need to do. Currently the random generator is created inside Theory environment. I've tried switching to the generator in AbstractEnv as recommended in your guidelines, but then I can no longer reproduce results across runs. I'll look into it over the weekend and will get back to you once it's fixed if that's okay :)

**Comment by ndangtt** [comment]
Thanks @TheEimer! I've found the issue. The random generator used for the benchmark is now switched to `abstract_env.np_random`.

One thing I'd like to ask. Currently I set the default config (in `benchmarks/theory_benchmark.py`) with `seed_action_space=True` to ensure that we can always reproduce results by default. But in other benchmarks this parameter is not set, i.e., the action space is not seeded by default. Is there a reason why we do that? And should I switch `seed_action_space` back to `False` by default for this benchmark too?

**Comment by TheEimer** [comment]
If I recall correctly, the action spaces aren't seeded in case users are familiar with gym and want to use the action_space.sample() method to generate random policies. If it's seeded the result will of course be consistent which would be very unusal for gym environments. I would therefore still tend to not seed the action space unless you feel there's a good reason to do so?

**Comment by ndangtt** [comment]
Ah I see. Thanks for clarifying it. I've switched the default setting back to unseeded action space now. Users can set it to True if they want reproducibility for DDQN training as noted in in `examples.py`. I think I'm good with this PR, unless there's something else you may want me to update :)

**Pull request merged**
